apps/article/urls.py
from django.urls import path
from article import views

app_name = "article"

urlpatterns = [
	path('', views.CategoryListView.as_view(), name="category_list"),
	path('search_results/', views.SearchResultsView.as_view(), name="search_results"),

	path('<slug:category>/', views.ArticleListView.as_view(), name="article_list"),
	path('<slug:category>/<slug:article>', views.ArticleDetailView.as_view(), name="article_detail"),
]

profile_store_article/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path, include


admin.site.login = staff_member_required(admin.site.login, login_url=settings.LOGIN_URL)

urlpatterns = [
    path('varbed/', admin.site.urls),

    path('', include('apps.user_profile.urls')),
    path('store/', include('apps.store.urls')),
    path('articles/', include('apps.article.urls')),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/article/models.py
from ckeditor.fields import RichTextField
from cloudinary.models import CloudinaryField

from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone


class Category(models.Model):
	name = models.CharField(max_length=30)
	slug = models.SlugField(unique=True, blank=True)
	is_active = models.BooleanField(default=True)

	def __str__(self):
		return f"{self.name}"

	def save(self, *args, **kwargs):
		self.slug = self.slug or slugify(self.name)
		super().save(*args, **kwargs)


class Article(models.Model):
	category = models.ForeignKey(
		Category,
		on_delete=models.PROTECT,
	)

	title = models.CharField(max_length=50)
	description = models.CharField(max_length=100)
	body = RichTextField()
	image = CloudinaryField(blank=True, null=True)
	author = models.CharField(max_length=50)
	date_pub = models.DateTimeField(default=timezone.now)
	slug = models.SlugField(unique=True, blank=True)
	is_active = models.BooleanField(default=True)

	def __str__(self):
		return f"{self.title}: {self.description}"

	def save(self, *args, **kwargs):
		self.slug = self.slug or slugify(self.title)
		super().save(*args, **kwargs)

apps/article/views.py
import datetime

from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic import (
	DetailView,
	FormView,
	ListView,
	TemplateView,
	UpdateView,
	View
)

from .models import *
from .utils.mixins.access import *


class CategoryListView(ListView):
	model = Category
	queryset = Category.objects.order_by('name')
	template_name = "article/category_list.html"


class ArticleListView(ArticleListAccessMixin, ListView):
	model = Article
	template_name = "article/article_list.html"

	def setup(self, request, *args, **kwargs):
		self.category = Category.objects.get(slug=kwargs['category'])
		return super().setup(request, *args, **kwargs)

	def get_queryset(self):
		qs = Article.objects.filter(category__slug=self.category.slug, is_active=True)
		return qs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['category'] = self.category

		return context


class ArticleDetailView(ArticleDetailAccessMixin, DetailView):
	model = Article
	template_name = "article/article_detail.html"
	slug_field = 'slug'
	slug_url_kwarg = 'article'

	def setup(self, request, *args, **kwargs):
		self.category = Category.objects.get(slug=kwargs['category'])
		return super().setup(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		current_article_id = self.get_object().id
		slug = self.kwargs['category']

		context['article_list'] = Article.objects.filter(
			category__slug=slug, is_active=True
		).exclude(
			id=current_article_id
		).order_by('-date_pub')[:3]
		
		return context


class SearchResultsView(ListView):
	model = Article
	template_name = "article/search_results.html"

	def get_queryset(self):
		if self.request.method == 'GET':
			query = self.request.GET.get('search_input')
			result = Article.objects.filter(Q(title__icontains=query))
			return result

		return Article.Objects.all().order_by('-date_pub')

apps/article/templates/article/article_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load article_template_tags %}
{% load static %}


<head>
	{% block title %}{{article.title}}{% endblock %}
</head>

<body>				
	{% block article %}active{% endblock %}


	{% block body %}
		<div class="center p-md-5 border-l-grey mw-1000 border-round">
			<div class="row">

				<div class="col-md-8">
					<h3>{{article.title}}</h3>
					<img class="img-fluid mh-300" src="{{article.image.url}}" alt="article.title">

					<!-- Span for image -->
					<p class="text-14 font-weight-bold mt-1">{{article.date_pub.day}} {{article.date_pub.month|month_name}} {{article.date_pub.year}}</p>
					
					<h4>{{article.description}}</h4>
				</div>

			</div>
			<hr>

			<div id="article-body">{{ article.body|safe}}</div>
			<hr>

			<div class="center mw-470">
				<b><center class="text-18 mb-1">Recent {{article.category.name}} Article</center></b>
				<ul>
					{% for article in article_list %}
						<li><a class="font-weight-bold text-14" href="{% url 'article:article_detail' category=article.category.slug article=article.slug %}">{{article.title}}: {{article.description}}</a></li>
					{% endfor %}
				</ul>
				<hr>
			</div>

			<center><a align="center" href="{% url 'article:article_list' article.category.slug %}">Go back to {{article.category.name}} home page</a></center>
		</div>
	{% endblock body %}
</body>

apps/article/templates/article/article_list.html
{% extends 'base.html' %}
{% load article_template_tags %}
{% load static%}

<head>
	{% block title %}Article List{% endblock %}
</head>

<body>
	{% block article %}active{% endblock %}

	{% block body %}
		<h3 align="center">{{category.name}}</h3>
		<hr>

		<form method="GET" action="{% url 'article:search_results' %}" class="float-right">
			<input name="search_input" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
		</form><br><br>

		<div class="row col pos-rel mt-2 t-20">
			{% for article in article_list %}
			  <div class="col-lg-4 col-md-6 mb-4">
			    <div class="card">

			      <div class="view overlay">
			        <a href="{% url 'article:article_detail' category=article.category.slug article=article.slug %}">
			        	<img class="card-img-top" src="{{article.image.url}}" alt="{{article.title}}" >
			        </a>
			      </div>

			      <div class="card-list-body">
			        <a href="{% url 'article:article_detail' category=article.category.slug article=article.slug %}" class="dark-grey-text lead font-weight-bold text-26">{{article.title}}</a>
			      </div>

			    </div>
			  </div>
			{% endfor %}
		</div>
		<hr>
		<center><a align="center" href="{% url 'article:category_list' %}">Go back to Category List home page</a></center>

	{% endblock body %}


</body>

apps/article/templates/article/category_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load article_template_tags %}
{% load static %}


<head>
	{% block title %}Article{% endblock %}
</head>

<body>
	{% block article %}active{% endblock %}


	{% block body %}
		<h3 align="center">article</h3>
		<hr>

		<form method="GET" action="{% url 'article:search_results' %}" class="float-right">
			<input name="search_input" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
		</form><br><br>


		<div class="center mw-1000">
			<div class="row pos-rel mt-2 t-20">
				{% for category in category_list %}

					<div class="center col-4 mt-2">
						<h4 align="center">
							<a href="{% url 'article:article_list' category.slug%}">{{category.name}}</a>
						</h4>

						<div id="article-card" class="card border-round">
							{% with category.article_set.all|first as first_article %}
								<a href="{% url 'article:article_detail' category=category.slug article=first_article.slug %}">
									<img class="img-fluid img-rounded" src="{{first_article.image.url}}" alt="{{first_article.title}}">
								</a>
							{% endwith %}

							{% for article in category.article_set.all|slice:"0:4" %}
								<div class="card-list-body font-weight-bold">
									<a href="{% url 'article:article_detail' category=category.slug  article=article.slug %}">{{article.title}}: {{article.description}}</a>
								</div>
								<hr>
							{% endfor %}
						</div>

					</div>
				{% endfor %}
			</div>
		</div>

	{% endblock body %}
</body>

apps/article/templates/article/search_results.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load article_template_tags %}
{% load static %}


<head>
	{% block title %}Article Search Results{% endblock %}
</head>

<body>
	{% block article %}active{% endblock %}


	{% block body %}
		<h3 align="center">Article Search Results<span id="search-parameter"></span></h3>
		<hr>
		
		<form method="GET" action="{% url 'article:search_results' %}" class="float-right">
			<input name="search_input" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
		</form><br><br>

		<div class="center mw-470 mt-2">
			{% for article in article_list %}
				<div id="article-card" class="card border-round">
					<a href="{% url 'article:article_detail' category=article.category.slug article=article.slug %}">
						<img class="img-fluid img-rounded" src="{{article.image.url}}" alt="{{article.title}}">
					</a>
					<div class="card-list-body font-weight-bold">
						<span class="text-14">{{article.date_pub.day}} {{article.date_pub.month|month_name}} {{article.date_pub.year}}</span><br>
						<a href="{% url 'article:article_detail' category=article.category.slug article=article.slug %}">{{article.title}}: {{article.description}}</a>
					</div>
				</div><br>
			{% endfor %}
		</div>
	{% endblock body %}
</body>