apps/article/urls.py
from django.urls import path
from article import views

app_name = "article"

urlpatterns = [
	path('', views.CategoryListView.as_view(), name="category_list"),
	path('search_results/', views.SearchResultsView.as_view(), name="search_results"),

	path('<slug:category>/', views.ArticleListView.as_view(), name="article_list"),
	path('<slug:category>/<slug:article>', views.ArticleDetailView.as_view(), name="article_detail"),
]

apps/store/urls.py
from django.urls import path
from store import views

app_name='store'

urlpatterns = [	
	path('billing_profile/', views.BillingProfileView.as_view(), name='billing_profile'),
	path('cards/', views.CardView.as_view(), name='card'),
	path('shipping_address/', views.ShippingAddressView.as_view(), name='shipping_address'),
	path('order_history/', views.OrderHistoryView.as_view(), name='order_history'),

	path('order_summary/', views.OrderSummaryView.as_view(), name='order_summary'),
	path('checkout/', views.CheckoutView.as_view(), name='checkout'),

	path('', views.ItemCategoryListView.as_view(), name='item_category_list'),
	path('search_results/', views.SearchResultsView.as_view(), name='search_results'),

	path('<slug:item_category>/', views.ItemListView.as_view(), name='item_list'),
	path('<slug:item_category>/<slug:item>/', views.ItemDetailView.as_view(), name='item_detail'),
]

apps/user_profile/urls.py
from django.urls import path
from user_profile import views

app_name="profile"


urlpatterns = [	
    path('register/', views.CustomRegistrationView.as_view(), name="register"),
    path('login/', views.CustomAuthenticationView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('password_change/', views.CustomPasswordChangeView.as_view(), name="password_change"),
    path('password_reset/', views.CustomPasswordResetView.as_view(), name="password_reset_request"),
    path('password_reset_confirm/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('recover_username/', views.RecoverUsernameView.as_view(), name="recover_username"),
    path('password_validation/', views.PasswordValidationView.as_view(), name='password_validation'),
    path('ajax_password_validation', views.ajax_password_validation_view, name='ajax_password_validation'),

    path('', views.HomeView.as_view(), name="home"),   
    path('add_phone/', views.AddPhoneView.as_view(), name="add_phone"),
    path('verify_phone/', views.PhoneVerificationView.as_view(), name='phone_verification'),
	path('profile/', views.ProfileView.as_view(), name="profile"),
    path('update_profile/', views.UpdateProfileView.as_view(), name="update_profile"),
]

profile_store_article/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path, include


admin.site.login = staff_member_required(admin.site.login, login_url=settings.LOGIN_URL)

urlpatterns = [
    path('varbed/', admin.site.urls),

    path('', include('apps.user_profile.urls')),
    path('store/', include('apps.store.urls')),
    path('articles/', include('apps.article.urls')),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/user_profile/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.template.defaultfilters import slugify
from django.utils import timezone

from phonenumber_field.modelfields import PhoneNumberField

from store.models import Customer


MAX_LOGIN_ATTEMPT = 4
MAX_LOCKOUT = 1

LOCKOUT_WAIT_TIME = 15
RESEND_WAIT_TIME = 15
VALIDATION_TIME_LIMIT = 1

class UserProfile(models.Model):
	user = models.OneToOneField(User, related_name='userprofile', on_delete=models.CASCADE, blank=True, null=True)
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	email = models.EmailField(max_length=50)
	slug = models.SlugField(unique=True)
	
	login_attempt = models.IntegerField(default=0)
	login_attempt_time = models.DateTimeField(default=timezone.now)
	login_lockout = models.IntegerField(default=0)
	send_msg_time = models.DateTimeField(default=timezone.now)

	phonenumber = PhoneNumberField(null=True, blank=True, unique=True)
	service_sid = models.CharField(max_length=50, null=True, blank=True)
	verified_number = models.BooleanField(default=False)

	def __str__(self):
		string = ''
		if not self.user.is_active:
			string = ' (deactivated)'
		return f"{self.first_name} {self.last_name}{string}"

	def save(self, *args, **kwargs):
		self.first_name = self.user.first_name 
		self.last_name = self.user.last_name
		self.email = self.user.email

		if self.user is not None:
			self.slug = self.slug or slugify(self.user.username)

		customer_qs = Customer.objects.filter(user=self.user)
		if customer_qs.exists():
			customer_qs[0].save()


		super().save(*args, **kwargs)


	# Logging in
	def add_attempt(self):
		self.login_attempt += 1
		self.login_attempt_time = timezone.now()
		self.save()

		return self

	def add_lockout(self):
		self.login_attempt = 0
		self.login_lockout += 1
		self.save()

		return self

	def reset_values(self):
		self.login_attempt = 0
		self.login_lockout = 0
		self.login_attempt_time = timezone.now()
		self.save()

		self.user.last_login = timezone.now()
		self.user.save()

		return self

	def temp_lockout(self):
		return self.login_attempt > MAX_LOGIN_ATTEMPT

	def perm_lockout(self):
		return self.login_lockout > MAX_LOCKOUT

	def lockout_over(self):
		time_dif = (timezone.now() - self.login_attempt_time).total_seconds() / 60  #minutes
		return time_dif > LOCKOUT_WAIT_TIME


	# Password validation
	def validation_required(self):
		time_dif = (timezone.now() - self.user.last_login).total_seconds() / 3600  #hours
		return time_dif > VALIDATION_TIME_LIMIT


	# Requesting password reset link or username
	def send_msg_time_dif(self):
		return (timezone.now() - self.send_msg_time).total_seconds()

	def send_msg_wait_time(self):
		return int(RESEND_WAIT_TIME - self.send_msg_time_dif())

	def allow_send_msg(self):
		return self.send_msg_time_dif() > RESEND_WAIT_TIME

	def is_showcase_user(self):
		return self.user.username == "Al"


	# Updating profile
	def set_phonenumber(self, phonenumber, service_sid):
		self.phonenumber = phonenumber
		self.service_sid = service_sid
		self.verified_number = False
		self.save()

	def verify_phonenumber(self):
		self.verified_number = True
		self.save()

	def disable_account(self):
		self.reset_values()
		self.user.is_active = False
		self.user.save()


def userprofile_reciever(sender, instance, created, *args, **kwargs):
	if created:
		userprofile = UserProfile.objects.create(user=instance)
post_save.connect(userprofile_reciever, sender=User)


@receiver(post_save, sender=User, dispatch_uid="update_userprofile")
def update_userprofile(sender, instance, **kwargs):
	instance.userprofile.save()


class UserStyle(models.Model):
	website = models.TextField()
	admin_page = models.TextField()

	def __str__(self):
		return "CSS"

apps/user_profile/utils/helper_functions/forms.py
import random, string

def random_string(k):
	token = ''.join(random.choices((string.ascii_lowercase + string.digits), k=k))
	return token

apps/user_profile/utils/mixins/forms.py
from crispy_forms.helper import FormHelper
from django import forms


class CrispyMixin:
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_show_labels = False


class CrispyRequestMixin(CrispyMixin):
	def __init__(self, request, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.request = request
		self.user = request.user
		self.profile = self.user.userprofile

apps/user_profile/utils/helper_functions/views.py
import json

from django.contrib import messages
from django.contrib.auth import logout
from django.urls import reverse


def deserialize_json(request):
	request.POST = request.POST.copy()
	json_data = json.loads(request.POST['json_data'])[1:]

	data = {}
	for element in json_data:
		request.POST[element['name']] = element['value']

	return request


def get_profile(request):
	email = request.session.get('email')
	phonenumber = request.session.get('phonenumber')

	profile = None
	if email is not None:
		profile = UserProfile.objects.get(email=email)
	
	elif phonenumber is not None:
		profile = UserProfile.objects.get(phonenumber=phonenumber)

	return profile


def check_for_lockout(request, profile):
	url = None
	if profile.temp_lockout():
		messages.warning(
			request,
			"You have attempted to log in too many times. Please try again later."
		)
		url = reverse('profile:login')
		logout(request)

	return url

apps/user_profile/utils/mixins/views.py
import json

from django.http import JsonResponse
from django.views.generic import FormView

from user_profile.forms import PasswordValidationForm



class RequestFormMixin:
	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs.update({'request': self.request})
		return kwargs



def json_response_with_errors(form):
	data = {'error_list': form.errors}
	return JsonResponse(data, status=200)


class AjaxValidateFormMixin:
	def form_valid(self, form):		
		# Returns empty error dict to front end to enable submit button
		if self.request.is_ajax():
			return json_response_with_errors(form)
		
		form.save()
		return super().form_valid(form)

	def form_invalid(self, form):
		# Ajax validation
		if self.request.is_ajax():
			return json_response_with_errors(form)

		return super().form_invalid(form)


class ChangePasswordFormMixin(RequestFormMixin, AjaxValidateFormMixin):
	def post(self, *args, **kwargs):
		profile = self.profile
		self.request.POST = self.request.POST.copy()

		self.request.POST['email'] = profile.email
		self.request.POST['username'] = profile.user.username
		self.request.POST['first_name'] = profile.first_name
		self.request.POST['last_name'] = profile.last_name

		return super().post(self.request, **kwargs)



class VerifyPasswordContextMixin:
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context_name = "verify_password"

		if self.profile.validation_required():
			context[context_name] = PasswordValidationForm(self.request)

		return context

apps/user_profile/templates/user_profile/add_phone.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

<head>
	{% block title %}Add Phone Number{% endblock %}
</head>

<body>
	{% block body %}
		<div class="center border-l-grey border-round w-290">
			<form method="POST" class="single-submit">
				{% csrf_token %}
				<h3 class="mb-3" align="center">Add Phone Number</h3>
				<div class="form-group">{{form.country_code}}{{form.area_code}}{{form.number}}</div>
				{% if form.phonenumber.errors %}
				    {% for err in form.phonenumber.errors %}
				      <p class= "text-error error_message mt-3">{{ err }}</p>
				    {% endfor %}
				{% endif %}
				
				<a class="cursor"><small>Why do you need my phone number?</small></a>
				<p class="text-14 mt-2 info">We will use your phone number as a means of reseting your password or recovering your username if you have issues with using your email.</p>
				<button type="submit" class="btn btn-primary w-250 mt-2">Add Phone Number</button>
				<span class="mt-3"><center>or</center></span>
				<hr>
			</form>

			<form method="POST">
				{% csrf_token %}
				<button type="submit" name="later" value="true" class="btn bt-color2 w-250">Add Phone Number Later</button>
			</form>

		</div>
	{% endblock body %}

	{% block javascript %}
		<script type="text/javascript">
			$(".info").hide()

			$(".cursor").on('click', function(){
				$(".info").show()
			});
		</script>
	{% endblock javascript %}
</body>

apps/user_profile/templates/user_profile/home.html
{% extends 'base.html' %}
{% load static %}



<body>
	{% block body %}

	<div align="center">
		<h3>Welcome to my Template Website</h3>
		<h4>Below are my applications which you can play around with</h4>
		
		<div class="row center mw-700">
			<a class="col" href="{% url 'profile:profile' %}">
				<img src="{% static 'user_profile/html_images/tintin_400.jpg' %}" alt="Profile" class="img-fluid">
				<h5>Profile</h5>
			</a>
			<a class="col" href="{% url 'store:item_category_list' %}">
				<img src="{% static 'user_profile/html_images/tintin_404.jpg' %}" alt="Store" class="img-fluid">
				<h5>Store</h5>
			</a>
			<a class="col" href="{% url 'article:category_list' %}">
				<img src="{% static 'user_profile/html_images/tintin_403.jpg' %}" alt="Article" class="img-fluid">
				<h5>Articles</h5>
			</a>
		</div>

	</div>


	{% endblock %}
</body>

apps/user_profile/templates/user_profile/phone_verification.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


<head>
	{% block title %}Verify Phone Number{% endblock %}
</head>

<body>
	{% block body %}
		<form class="single-submit center border-l-grey border-round mw-300" align="center" method="POST">
			{% csrf_token %}
			<h3>Verify Phone Number</h3>
			{{form.code|as_crispy_field}}
			<button type="submit" class="btn bt-color1 w-full" id="verify_text">Verify</button>
			<hr>
			<h6 class="text-14">Didn't recieve the code?</h6>
			<center>
				<button type="submit" name="resend_code" value="true" class="btn bt-color3 w-full">Resend Text</button>
				<hr>
				<a href="{% url 'profile:profile' %}">Back to profile</a>	
			</center>
		</form>
	{% endblock body %}
</body>

apps/user_profile/templates/user_profile/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load user_profile_template_tags %}
{% load static %}


<head>
	{% block title %}{{user.username}}'s Profile{% endblock %}
</head>

<body>
	{% block profile %}active{% endblock %}
	
	{% block body %}
		<div class="center border-l-grey border-round mw-300">
			<h3>{{ user.username }} <small class="text-14">({{user.first_name}} {{user.last_name}})</small></h3>
			<small class="text-14">Date joined: {{user.date_joined}}</small>
			<img class="img-fluid mt-2 mb-2" src="{% static 'user_profile/html_images/tintin_profile.jpg' %}">
			
			<a href="{% url 'profile:update_profile' %}">Update Profile</a><br>
			<a href="{% url 'profile:password_change' %}">Change Password</a><br>
			{% if user|show_verify %}
				<a href="{% url 'profile:phone_verification' %}">Verify Phone Number</a>
			{% endif %}
		</div>
	{% endblock body %}

	{% block javascript %}
		<script type="text/javascript">
			$(document).ready(function(){
				$("#update_account").show();
				$("#change_password").show();
				$verifyBtn = $("#verify_phone_number");
				if ($verifyBtn){
					$verifyBtn.show();
				}
			});
		</script>	
		<script src="{% static 'user_profile/js/reusable_code/verify_password.js' %}"></script>
	{% endblock javascript %}
</body>

apps/user_profile/templates/user_profile/update_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load user_profile_template_tags %}
{% load static %}


<head>
	{% block title %}Managing {{user.username}}'s Profile{% endblock %}
</head>

{% block profile %}active{% endblock %}

<body>
	{% block body %}
		<form method="POST" class="single-submit center border-l-grey border-round mw-300">
			{% csrf_token %}

			<h3><center>{{user.username}}</center></h3>

			<label for="id_first_name">First Name</label>
			{{form.first_name|as_crispy_field}}

			<label for="id_last_name">Last Name</label>
			{{form.last_name|as_crispy_field}}

			<label for="id_email">Email Address</label>
			{{form.email|as_crispy_field}}


			<hr>
			<h5 align="center">Current Phone Number</h5>
			<p align="center">
				{% if user.userprofile.phonenumber %}
					{{user.userprofile.phonenumber}}
					{% if not user.userprofile.verified_number %}
						(not yet verified)
					{% endif %}
				{% else %}
					Not yet set up
				{% endif %}
			</p>
			<hr>

			{{form.country_code}}{{form.area_code}}{{form.number}}

			{% if form.phonenumber.errors %}
			    {% for err in form.phonenumber.errors %}
			      <p class= "text-error error_message mt-3">{{ err }}</p>
			    {% endfor %}
			{% endif %}


			<button type="submit" class="btn bt-color1 w-full mt-4" id="update_btn">Update</button>
			<button type="submit" class="btn btn-danger w-full mt-2" name="disable" value="True" id="disable_btn">Disable Account</button>
			<hr>
			<a class="center-block" href="{% url 'profile:profile' %}"><center>Back to profile</center></a>
		</form>
	{% endblock body %}

	{% block javascript %}
		<script type="text/javascript">
			$("#disable_btn").on("click", function() {
				val = window.confirm("Are you sure you want to disable your account?");
				return val
			});
		</script>
		<script src="{% static 'user_profile/js/reusable_code/verify_password.js' %}"></script>
	{% endblock javascript %}
</body>

apps/user_profile/templates/user_profile/verify_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


<head>
	{% block title %}Verify Password{% endblock %}
</head>

<body>
	{% block body %}
		<div class="center mw-300">
			<form method="POST" class="single-submit center">
				{% csrf_token %}
				<h4 align="center">Please verify your password</h4>
				{{form|crispy}}
				<button type="submit" class="btn bt-color1 w-full">Verify Password</button>
			</form>
		</div>
	{% endblock body %}
</body>