apps/store/urls.py
from django.urls import path
from store import views

app_name='store'

urlpatterns = [	
	path('billing_profile/', views.BillingProfileView.as_view(), name='billing_profile'),
	path('cards/', views.CardView.as_view(), name='card'),
	path('shipping_address/', views.ShippingAddressView.as_view(), name='shipping_address'),
	path('order_history/', views.OrderHistoryView.as_view(), name='order_history'),

	path('order_summary/', views.OrderSummaryView.as_view(), name='order_summary'),
	path('checkout/', views.CheckoutView.as_view(), name='checkout'),

	path('', views.ItemCategoryListView.as_view(), name='item_category_list'),
	path('search_results/', views.SearchResultsView.as_view(), name='search_results'),

	path('<slug:item_category>/', views.ItemListView.as_view(), name='item_list'),
	path('<slug:item_category>/<slug:item>/', views.ItemDetailView.as_view(), name='item_detail'),
]

profile_store_article/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path, include


admin.site.login = staff_member_required(admin.site.login, login_url=settings.LOGIN_URL)

urlpatterns = [
    path('varbed/', admin.site.urls),

    path('', include('apps.user_profile.urls')),
    path('store/', include('apps.store.urls')),
    path('articles/', include('apps.article.urls')),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/store/models.py
from cloudinary.models import CloudinaryField
from dateutil.relativedelta import relativedelta

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models.signals import post_save
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone
from django.utils.html import format_html

from django_countries.fields import CountryField
from math import floor

from .utils.helper_functions.models import *


PURCHASE_WAIT_TIME = 5


class Customer(models.Model):
	user = models.OneToOneField(
		User, related_name='customer', on_delete=models.CASCADE, blank=True, null=True
	)

	full_name = models.CharField(max_length=100, default="Guest")
	email = models.EmailField(max_length=50, blank=True, null=True)
	stripe_customer_id = models.CharField(max_length=100, blank=True, null=True)

	purchase_attempt_time = models.DateTimeField(default=timezone.now)
	guest_num = models.IntegerField(default=0, blank=True, null=True)

	def __str__(self):
		return f"{self.full_name}"

	def save(self, *args, **kwargs):
		if self.user is not None:
			self.full_name = f"{self.user.first_name} {self.user.last_name}"
			self.email = self.user.email
			self.guest_num = None

		super().save(*args, **kwargs)
		return self

	def stripe_time_dif(self):
		return (timezone.now()-self.purchase_attempt_time).total_seconds()

	def stripe_wait_time(self):
		return int(PURCHASE_WAIT_TIME - self.stripe_time_dif())

	def stripe_enabled(self):
		return self.stripe_time_dif() > PURCHASE_WAIT_TIME


class Card(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
	src_id = models.CharField(max_length=30)

	line1 = models.CharField(max_length=30)
	line2 = models.CharField(max_length=30, blank=True, null=True)
	city = models.CharField(max_length=30)
	state = models.CharField(max_length=30)
	zipcode = models.CharField(max_length=20)
	country = CountryField(multiple=False)

	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=30)
	email = models.EmailField(max_length=30)

	def __str__(self):
		return f"{self.first_name} {self.last_name}: {self.src_id}"


class ShippingAddress(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.CASCADE)

	line1 = models.CharField(max_length=30)
	line2 = models.CharField(max_length=30, blank=True, null=True)
	city = models.CharField(max_length=30)
	state = models.CharField(max_length=30)
	zipcode = models.CharField(max_length=30)
	country = CountryField(multiple=False)

	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=30)
	email = models.EmailField(max_length=30)

	def __str__(self):
		if self.line2:
			address = f"{self.line1}, {self.line2}, {self.city}, {self.state}, {self.zipcode}, {self.country}"
		else:
			address = f"{self.line1}, {self.city}, {self.state}, {self.zipcode}, {self.country}"

		return address


class ItemCategory(models.Model):
	name = models.CharField(max_length=30, unique=True)
	slug = models.SlugField(unique=True, blank=True)
	date_started = models.DateTimeField(default=timezone.now)
	is_active = models.BooleanField(default=True)

	total_earnings = models.IntegerField(default=0)
	daily_earnings = models.IntegerField(default=0)
	weekly_earnings = models.IntegerField(default=0)
	monthly_earnings = models.IntegerField(default=0)
	yearly_earnings = models.IntegerField(default=0)

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.inital_name = self.name

	def __str__(self):
		return f"{self.name}"

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super().save(*args, **kwargs)

	def get_time_since_started(self):
		total_time = timezone.now() - self.date_started
		
		days = total_time.days
		weeks = floor(days / 7)
		months = floor(days / 31)
		years = floor(days / 365)

		total_time_str = f"""
			Store open for: {years} years,
			{months} months, {days} days
			"""
		return [days, total_time_str]

	def record_stats(self):
		total_earnings = 0
		daily_earnings = 0
		weekly_earnings = 0
		monthly_earnings = 0
		yearly_earnings = 0

		for item in Item.objects.filter(item_category=self):
			total_earnings += item.total_earnings
			daily_earnings += item.daily_earnings
			weekly_earnings += item.weekly_earnings
			monthly_earnings += item.monthly_earnings
			yearly_earnings += item.yearly_earnings

		self.total_earnings = total_earnings
		self.daily_earnings = daily_earnings
		self.weekly_earnings = weekly_earnings
		self.monthly_earnings = monthly_earnings
		self.yearly_earnings = yearly_earnings

		self.save()

	def filter_category_link(self):
		if self.pk:
		
			html_content = ''
			for filter_category in self.filtercategory_set.all():
				url = reverse('admin:store_filtercategory_change', args=(filter_category.pk,))
				html_content += '<a href="{}">{}</a><br>'.format(url, filter_category.name)

			add_url = reverse('admin:store_filtercategory_add')
			html_content += '<br><b><a href="%s">Add New Category</a></b>' % add_url

			return format_html(html_content)

		return ''

	filter_category_link.short_description = "Filter Categories"


class FilterCategory(models.Model):
	item_category = models.ForeignKey(
		ItemCategory,
		on_delete=models.CASCADE
	)
	name = models.CharField(max_length=30, unique=True)

	def __str__(self):
		return f"{self.item_category}: {self.name}"

	def item_category_link(self):
		if self.pk:
			url = reverse('admin:store_itemcategory_change', args=(self.item_category.pk,))
			html_content = '<br><b><a href="{}">Go back to {}</a></b>'.format(url, self.item_category.name)

			return format_html(html_content)

		return ''

	item_category_link.short_description = ""


class FilterOption(models.Model):
	filter_category = models.ForeignKey(
		FilterCategory,
		on_delete=models.CASCADE
	)
	name = models.CharField(max_length=30, unique=True)

	def __str__(self):
		return f"{self.filter_category.name}: {self.name}"



class Item(models.Model):
	item_category = models.ForeignKey(
		ItemCategory,
		on_delete=models.CASCADE
		)
	filter_option = models.ManyToManyField(FilterOption, blank=True)

	name = models.CharField(max_length=50, unique=True)
	description = models.TextField()
	price = models.FloatField(default=0)
	discount_price = models.FloatField(blank=True, null=True)
	quantity = models.PositiveIntegerField(default=0, validators=[MinValueValidator(1)])
	image = CloudinaryField(blank=True, null=True)
	slug = models.SlugField(blank=True, null=True, unique=True)
	is_active = models.BooleanField(default=True)

	total_sold = models.IntegerField(default=0)
	total_earnings = models.IntegerField(default=0)
	daily_earnings = models.IntegerField(default=0)
	weekly_earnings = models.IntegerField(default=0)
	monthly_earnings = models.IntegerField(default=0)
	yearly_earnings = models.IntegerField(default=0)	

	def __str__(self):
		return f"{self.name} ({self.quantity} in stock)"

	def save(self, *args, **kwargs):
		self.slug = self.slug or slugify(self.name)
		super().save(*args, **kwargs)

		return self

	def clean_fields(self, exclude=None):
		if self.quantity < 0:
			raise ValidationError({'quantity': "Quantity can't be negative."})

	def in_stock(self):
		if self.quantity > 0:
			return True

		return False

	def get_total_sold(self):
		quantity = 0
		for order_item in self.orderitem_set.filter(ordered=True, in_cart=True):
			quantity += order_item.quantity

		return quantity

	def get_total_earnings(self):
		total_earnings = 0
		for order_item in self.orderitem_set.filter(ordered=True, in_cart=True):
			total_earnings += order_item.get_price_total()

		return total_earnings

	def get_rate(self, time_rate):
		total_days = self.item_category.get_time_since_started()[0]
		if total_days == 0:
			total_days = 1

		rate = round((self.get_total_earnings() / total_days) * time_rate, 2)
		
		return rate

	def record_stats(self):
		self.total_sold = self.get_total_sold()
		self.total_earnings = self.get_total_earnings() 
		self.daily_earnings = self.get_rate(1)
		self.weekly_earnings = self.get_rate(7)
		self.monthly_earnings = self.get_rate(31)
		self.yearly_earnings = self.get_rate(365)
		self.save()


class Order(models.Model):
	customer = models.ForeignKey(
		Customer,
		on_delete=models.CASCADE,
	)
	shipping_address = models.ForeignKey(
		ShippingAddress,
		on_delete=models.CASCADE,
		blank=True,
		null=True
	)
	card = models.ForeignKey(
		Card,
		on_delete=models.CASCADE,
		blank=True,
		null=True
	)

	full_name = models.CharField(max_length=100, blank=True, null=True)
	email = models.CharField(max_length=30, blank=True, null=True)

	payment_intent_id = models.CharField(max_length=30, blank=True, null=True)
	ref_code = models.CharField(max_length=20, blank=True, null=True)
	date = models.DateTimeField(blank=True, null=True)

	ordered = models.BooleanField(default=False)
	delivered = models.BooleanField(default=False)
	recieved = models.BooleanField(default=False)
	refund_requested = models.BooleanField(default=False)
	refund_granted = models.BooleanField(default=False)
	cancelled = models.BooleanField(default=False)

	def __str__(self):
		string = ''
		if self.cancelled:
			string = ' (cancelled)'

		return f"Order of {self.full_name}{string}"

	def save(self, *args, **kwargs):
		self.full_name = self.customer.full_name
		super().save(*args, **kwargs)

		return self

	def get_price_total(self):
		price_total = 0
		for order_item in self.orderitem_set.all():
			price_total += order_item.get_price_total()

		return price_total

	def get_order_description(self):
		description_list = []
		for order_item in self.orderitem_set.all():
			item = order_item.item
			description_list.append(
				f"{order_item.quantity} order(s) of {item.name}: ${item.price}"
			)

		description_str = ', '.join(description_list)

		return [description_list, description_str] 

apps/store/utils/helper_functions/models.py
import random, string


def create_ref_code():
	ref_code = ''.join(random.choices((string.ascii_lowercase + string.digits), k=20))
	return ref_code

apps/store/forms.py
from crispy_forms.helper import FormHelper

from django import forms
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.utils import timezone

from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

from user_profile.models import UserProfile
from user_profile.utils.mixins.forms import CrispyMixin

from .models import *
from .utils.helper_functions.forms import *
from .utils.helper_functions.stripe import *
from .utils.mixins.forms import *


class QuantityForm(CrispyMixin, forms.Form):
	quantity = forms.IntegerField(required=False)

	def clean_quantity(self):
		quantity = self.cleaned_data.get('quantity')
		if quantity < 1:
			raise forms.ValidationError("Enter a valid quantity.")

		return quantity



class StoredAddressForm(CrispyMixin, forms.Form):
	def __init__(self, customer, *args, **kwargs):
		super().__init__(*args, **kwargs)

		self.fields['stored_address'] = forms.ModelChoiceField(
			queryset=ShippingAddress.objects.filter(customer=customer),
			empty_label="",
			widget=forms.Select(attrs={'style': 'width:400px;'})
		)

		if ShippingAddress.objects.filter(customer=customer).count() > 0:
			self.fields['stored_address'].empty_label = "Select Shipping Address"


class StoredCardForm(CrispyMixin, forms.Form):
	def __init__(self, request, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['stored_card'] = forms.ChoiceField(
			choices=stored_card_choices(request),
			widget=forms.Select(
				attrs={'style': 'width:400px;'}
			)
		)


ADDRESS_CHOICES = (
	('Choose Address', 'Choose Address'),
	('Use New Address', 'Use New Address')
)

CARD_CHOICES = (
	('Choose Card', 'Choose Card'),
	('Use New Card', 'Use New Card')
)

class ShippingAddressForm(CrispyCustomerMixin, forms.Form):
	line1 = forms.CharField(
		max_length=30,
		widget=forms.TextInput(
			attrs={'placeholder': '9764 Jeopardy Lane'}
		)
	)
	line2 = forms.CharField(
		required=False,
		max_length=30,
		widget=forms.TextInput(
			attrs={'placeholder': 'Apartment or Suite'}
		)
	)
	city = forms.CharField(
		max_length=30,
		widget=forms.TextInput(
			attrs={'placeholder': 'Chicago'}
		)
	)
	state = forms.CharField(
		max_length=30,
		widget=forms.TextInput(
			attrs={'placeholder': 'IL'}
		)
	)
	zipcode = forms.CharField(
		max_length=30,
		widget=forms.TextInput(
			attrs={'placeholder': '60611'}))

	country = CountryField(
		blank_label='(select country)').formfield(initial='US'
	)

	first_name = forms.CharField(max_length=30)
	last_name = forms.CharField(max_length=30)
	email = forms.EmailField(max_length=30)

	address_option = forms.ChoiceField(
		required=False,
		choices=ADDRESS_CHOICES,
		initial=ADDRESS_CHOICES[0][0],
		widget=forms.RadioSelect()
	)

	def save(self):
		clean = self.cleaned_data
		address = ShippingAddress.objects.get_or_create(
			customer=self.customer,
			line1=clean['line1'],
			line2=clean['line2'],
			city=clean['city'],
			state=clean['state'],
			zipcode=clean['zipcode'],
			country=clean['country'],
			first_name=clean['first_name'],
			last_name=clean['last_name'],
			email=clean['email']
		)[0]
	
		return address

	def update(self, address):
		clean = self.cleaned_data
		address_pk = ShippingAddress.objects.filter(pk=address.pk).update(
			line1=clean['line1'],
			line2=clean['line2'],
			city=clean['city'],
			state=clean['state'],
			zipcode=clean['zipcode'],
			country=clean['country'],
			first_name=clean['first_name'],
			last_name=clean['last_name'],
			email=clean['email']
		)
				
		return address_pk


class BillingAddressForm(CrispyCustomerMixin, forms.Form):
	billing_line1 = forms.CharField(
		max_length=30,
		widget=forms.TextInput(
			attrs={'placeholder':  '1234 Main St'}
		)
	)
	billing_line2 = forms.CharField(
		required=False,
		max_length=30,
		widget=forms.TextInput(
			attrs={'placeholder': 'Apartment or Suite'}
		)
	)
	billing_city = forms.CharField(max_length=30)
	billing_state = forms.CharField(max_length=30)
	billing_zipcode = forms.CharField(max_length=30)
	billing_country = CountryField(
		blank_label='(select country)'
	).formfield(initial='US')

	billing_first_name = forms.CharField(max_length=30)
	billing_last_name = forms.CharField(max_length=30)
	billing_email = forms.EmailField(max_length=30)

	card_option = forms.ChoiceField(
		required=False,
		choices=CARD_CHOICES,
		initial=CARD_CHOICES[0][0],
		widget=forms.RadioSelect()
	)

	def save(self, stripe_src):
		clean = self.cleaned_data
		val = stripe_add_card(self.customer, stripe_src, clean)

		src_id = val[0]
		new_card = val[1]

		if new_card:
			card = Card.objects.create(
				customer=self.customer,
				src_id=src_id,
				line1=clean['billing_line1'],
				line2=clean['billing_line2'],
				city=clean['billing_city'],
				state=clean['billing_state'],
				zipcode=clean['billing_zipcode'],
				country=clean['billing_country'],
				first_name=clean['billing_first_name'],
				last_name=clean['billing_last_name'],
				email=clean['billing_email']
			)
		else:
			card = Card.objects.get(src_id=src_id)

		return card

	def update(self, card):
		clean = self.cleaned_data
		stripe_update_card(self.customer, card, clean)

		card_pk = Card.objects.filter(pk=card.pk).update(
			line1=clean['billing_line1'],
			line2=clean['billing_line2'],
			city=clean['billing_city'],
			state=clean['billing_state'],
			zipcode=clean['billing_zipcode'],
			country=clean['billing_country'],
			first_name=clean['billing_first_name'],
			last_name=clean['billing_last_name'],
			email=clean['billing_email']
		)

		return card_pk

	def make_payment(self, order, card, address):
		payment_intent_id = make_payment(order, card, address)
		order.record_payment(card, address, payment_intent_id)
		# send_order_email(order)

apps/store/utils/mixins/forms.py
from user_profile.utils.mixins.forms import CrispyMixin

class CrispyCustomerMixin(CrispyMixin):
	def __init__(self, customer, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.customer = customer

apps/store/templates/store/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


<head>
	{% block title %}Checkout{% endblock %}
</head>

<body>
	{% block order_summary %}active{% endblock %}

	{% block body %}

		<!-- JS Disabled -->
		<noscript>
			<meta HTTP-EQUIV="REFRESH" content="0; url={% url 'store:order_summary' %}">
		</noscript>

		<script src="https://js.stripe.com/v3/"></script>

		<form method="POST" class="" id="stripe-form">
			{% csrf_token %}

			<div class="center border-l-grey border-round mw-300">
				<h3 align="center">Shipping Form</h3>
				
				{% if user.is_authenticated %}
					<span id="user-exists"></span>
					<label for="id_address_option">Address Option:</label>
					{{shipping_form.address_option|as_crispy_field}}
					
					<div id="shipping-choices">
						<select name="stored_address" id="id_stored_address" class="form-control">
						{% for x, y in stored_address_list.fields.stored_address.choices %}
						    <option value="{{ x }}"{% if form.fields.customer.value == x %} selected{% endif %}>{{ y }}</option>
						{% endfor %}
						</select>
					</div>
				{% endif %}

				<div id="shipping-form">

					{% if shipping_form.non_field_errors %}
					  <div class="alert alert-danger">
					    {% for err in shipping_form.non_field_errors %}
					      <p>{{ err }}</p>
					    {% endfor %}
					  </div>
					{% endif %}

					<label for="id_line1">Line 1</label>
					{{shipping_form.line1|as_crispy_field}}

					<label for="id_line2">Line 2 (optional)</label>
					{{shipping_form.line2|as_crispy_field}}<br>

					<label for="id_city">City</label>
					{{shipping_form.city|as_crispy_field}}

					<label for="id_state">State</label>
					{{shipping_form.state|as_crispy_field}}

					<label for="id_zipcode">Zip Code</label>
					{{shipping_form.zipcode|as_crispy_field}}

					<label for="id_country">Country</label>
					{{shipping_form.country|as_crispy_field}}<br>

					<label for="id_first_name">First Name</label>
					{{shipping_form.first_name|as_crispy_field}}

					<label for="id_last_name">Last Name</label>
					{{shipping_form.last_name|as_crispy_field}}

					<label for="id_email">Email Address</label>
					{{shipping_form.email|as_crispy_field}}
					<p id="email_error" class="text-error"></p><br>
				</div>

			</div>

			<div class="center border-l-grey border-round mw-300 mt-3">
				<h3 class="mt-3" align="center">Billing Form</h3>

				{% if user.is_authenticated %}
					<label for="id_card_option">Card Option:</label>
					{{billing_form.card_option|as_crispy_field}}

					<div id="card-choices">
						<select name="stored_card" id="id_stored_card" class="form-control">
						{% for x, y in stored_card_list.fields.stored_card.choices %}
						    <option value="{{ x }}"{% if form.fields.customer.value == x %} selected{% endif %}>{{ y }}</option>
						{% endfor %}
						</select>
					</div>
				{% endif %}

				<div id="billing-form">

					{% if billing_form.non_field_errors %}
					  <div class="alert alert-danger">
					    {% for err in billing_form.non_field_errors %}
					      <p>{{ err }}</p>
					    {% endfor %}
					  </div>
					{% endif %}

					<label for="id_billing_line1">Line 1</label>
					{{billing_form.billing_line1|as_crispy_field}}

					<label for="id_billing_line2">Line 2 (optional)</label>
					{{billing_form.billing_line2|as_crispy_field}}

					<label for="id_billing_city">City</label>
					{{billing_form.billing_city|as_crispy_field}}

					<label for="id_billing_state">State</label>
					{{billing_form.billing_state|as_crispy_field}}

					<label for="id_billing_zipcode">Zip Code</label>
					{{billing_form.billing_zipcode|as_crispy_field}}

					<label for="id_billing_country">Country</label>
					{{billing_form.billing_country|as_crispy_field}}					

					<label for="id_billing_first_name">First Name</label>
					{{billing_form.billing_first_name|as_crispy_field}}

					<label for="id_billing_last_name">Last Name</label>
					{{billing_form.billing_last_name|as_crispy_field}}

					<label for="id_billing_email">Email Address</label>
					{{billing_form.billing_email|as_crispy_field}}
					<p id="billing_email_error" class="text-error"></p><br>
				</div>
				
		         <!-- Payment Form -->
		        <div id="payment-form">
		          <h3>Payment</h3>
		          <label for="card-element">Credit or debit card</label>
		          <div id="card-element">
		            <!-- A Stripe Element will be inserted here. -->
		          </div>
		           <!-- Used to display form errors -->
		          <div id="card-errors" role="alert"></div>
		        </div>

			</div>
			<center>
		        <button type="submit" class="btn bt-color1 mw-300 mt-3" id="stripeBtn">Submit Payment</button>
		        <div class="loader mt-3 center"></div>
			</center>
		</form>

	{% endblock body %}

	{% block javascript %}
		<!-- Stripe Code -->
		<script type="text/javascript" src="{% static 'store/js/reusable_code/functions.js' %}"></script>
		<script type="text/javascript" src="{% static 'store/js/checkout.js' %}"></script>

		<script>var stripe = Stripe('{{PUB_KEY}}');</script>
		<script type="text/javascript" src="{% static 'store/js/stripe.js' %}"></script>
	{% endblock javascript %}
</body>

apps/store/templates/store/shipping_address.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


<head>
	{% block title %}Your Shipping Addresses{% endblock %}
</head>

<body>
	{% block profile %}active{% endblock %}

	{% block body %}
		<noscript>
			<meta HTTP-EQUIV="REFRESH" content="0; url={% url 'store:billing_profile' %}">
		</noscript>

		<div class="center border-l-grey border-round mw-300">
			<h3>Your Shipping Addresses</h3>
			<img class="img-fluid" src="{% static 'store/html_images/tintin_address.jpg' %}" alt="tintin_address">

			<select name="stored_address" id="id_stored_address" class="form-control">
			{% for x, y in stored_address_list.fields.stored_address.choices %}
			    <option value="{{ x }}"{% if form.fields.customer.value == x %}selected{% endif %}>{{ y }}</option>
			{% endfor %}
			</select>

			<button class="btn btn-success add-btn w-full">Add</button>

	    	{% for address, pk in address_form_list %}
	    		<form method="POST" id="{{pk}}" class="single-submit update-form">
	    			{% csrf_token %}

					<button type="button" class="btn btn-sm bt-color2 back-btn mt-3 mb-3">Back</button><br>

	    			<h3>Update Shipping Address</h3>

					{% if address.non_field_errors %}
					  <div class="alert alert-danger">
					    {% for err in address.non_field_errors %}
					      <p>{{ err }}</p>
					    {% endfor %}
					  </div>
					{% endif %}

					<input name="pk" value="{{pk}}" hidden>

					<label for="id_line1">Line 1</label>
					{{address.line1|as_crispy_field}}

					<label for="id_line2">Line 2 (optional)</label>
					{{address.line2|as_crispy_field}}
					<br>

					<label for="id_city">City</label>
					{{address.city|as_crispy_field}}

					<label for="id_state">State</label>
					{{address.state|as_crispy_field}}

					<label for="id_zipcode">Zip Code</label>
					{{address.zipcode|as_crispy_field}}

					<label for="id_country">Country</label>
					{{address.country|as_crispy_field}}
					<br>

					<label for="id_first_name">First Name</label>
					{{address.first_name|as_crispy_field}}

					<label for="id_last_name">Last Name</label>
					{{address.last_name|as_crispy_field}}

					<label for="id_email">Email Address</label>
					{{address.email|as_crispy_field}}
						
					<button type="submit" name="update" value="true" class="btn bt-color1 w-full mb-2">Update Address</button>
					<button type="submit" name="delete" value="true" class="btn btn-danger w-full">Delete</button>

	    		</form>
    		{% endfor %}

			<form method="POST" class="single-submit add-form">
				{% csrf_token %}

				<button type="button" class="btn btn-sm bt-color2 back-btn mt-3 mb-3">Back</button><br>

				<h3>Add New Shipping Address</h3>

				{% if form.non_field_errors %}
				  <div class="alert alert-danger">
				    {% for err in form.non_field_errors %}
				      <p>{{ err }}</p>
				    {% endfor %}
				  </div>
				{% endif %}

				<label for="id_line1">Line 1</label>
				{{form.line1|as_crispy_field}}

				<label for="id_line2">Line 2 (optional)</label>
				{{form.line2|as_crispy_field}}
				<br>

				<label for="id_city">City</label>
				{{form.city|as_crispy_field}}

				<label for="id_state">State</label>
				{{form.state|as_crispy_field}}

				<label for="id_zipcode">Zip Code</label>
				{{form.zipcode|as_crispy_field}}

				<label for="id_country">Country</label>
				{{form.country|as_crispy_field}}
				<br>

				<label for="id_first_name">First Name</label>
				{{form.first_name|as_crispy_field}}

				<label for="id_last_name">Last Name</label>
				{{form.last_name|as_crispy_field}}

				<label for="id_email">Email Address</label>
				{{form.email|as_crispy_field}}
				
				<button type="submit" name="add" value="true" class="btn bt-color1 w-full">Add Address</button>
			</form>

			<hr class="hr-light-blue">
	        <a href="{% url 'store:billing_profile' %}"><center>Back to billing profile</center></a>

		</div>

	{% endblock body %}

	{% block javascript %}
		<script type="text/javascript" src="{% static 'store/js/reusable_code/functions.js' %}"></script>
		<script type="text/javascript" src="{% static 'store/js/cards_and_shipping.js' %}"></script>
		<script src="{% static 'user_profile/js/reusable_code/verify_password.js' %}"></script>
	{% endblock javascript %}
</body>