apps/article/urls.py
from django.urls import path
from article import views

app_name = "article"

urlpatterns = [
	path('', views.CategoryListView.as_view(), name="category_list"),
	path('search_results/', views.SearchResultsView.as_view(), name="search_results"),

	path('<slug:category>/', views.ArticleListView.as_view(), name="article_list"),
	path('<slug:category>/<slug:article>', views.ArticleDetailView.as_view(), name="article_detail"),
]

apps/store/urls.py
from django.urls import path
from store import views

app_name='store'

urlpatterns = [	
	path('billing_profile/', views.BillingProfileView.as_view(), name='billing_profile'),
	path('cards/', views.CardView.as_view(), name='card'),
	path('shipping_address/', views.ShippingAddressView.as_view(), name='shipping_address'),
	path('order_history/', views.OrderHistoryView.as_view(), name='order_history'),

	path('order_summary/', views.OrderSummaryView.as_view(), name='order_summary'),
	path('checkout/', views.CheckoutView.as_view(), name='checkout'),

	path('', views.ItemCategoryListView.as_view(), name='item_category_list'),
	path('search_results/', views.SearchResultsView.as_view(), name='search_results'),

	path('<slug:item_category>/', views.ItemListView.as_view(), name='item_list'),
	path('<slug:item_category>/<slug:item>/', views.ItemDetailView.as_view(), name='item_detail'),
]

apps/user_profile/urls.py
from django.urls import path
from user_profile import views

app_name="profile"


urlpatterns = [	
    path('register/', views.CustomRegistrationView.as_view(), name="register"),
    path('login/', views.CustomAuthenticationView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('password_change/', views.CustomPasswordChangeView.as_view(), name="password_change"),
    path('password_reset/', views.CustomPasswordResetView.as_view(), name="password_reset_request"),
    path('password_reset_confirm/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('recover_username/', views.RecoverUsernameView.as_view(), name="recover_username"),
    path('password_validation/', views.PasswordValidationView.as_view(), name='password_validation'),
    path('ajax_password_validation', views.ajax_password_validation_view, name='ajax_password_validation'),

    path('', views.HomeView.as_view(), name="home"),   
    path('add_phone/', views.AddPhoneView.as_view(), name="add_phone"),
    path('verify_phone/', views.PhoneVerificationView.as_view(), name='phone_verification'),
	path('profile/', views.ProfileView.as_view(), name="profile"),
    path('update_profile/', views.UpdateProfileView.as_view(), name="update_profile"),
]

profile_store_article/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path, include


admin.site.login = staff_member_required(admin.site.login, login_url=settings.LOGIN_URL)

urlpatterns = [
    path('varbed/', admin.site.urls),

    path('', include('apps.user_profile.urls')),
    path('store/', include('apps.store.urls')),
    path('articles/', include('apps.article.urls')),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/user_profile/utils/helper_functions/forms.py
import random, string

def random_string(k):
	token = ''.join(random.choices((string.ascii_lowercase + string.digits), k=k))
	return token

apps/user_profile/utils/mixins/forms.py
from crispy_forms.helper import FormHelper
from django import forms


class CrispyMixin:
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_show_labels = False


class CrispyRequestMixin(CrispyMixin):
	def __init__(self, request, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.request = request
		self.user = request.user
		self.profile = self.user.userprofile

apps/user_profile/utils/helper_functions/views.py
import json

from django.contrib import messages
from django.contrib.auth import logout
from django.urls import reverse


def deserialize_json(request):
	request.POST = request.POST.copy()
	json_data = json.loads(request.POST['json_data'])[1:]

	data = {}
	for element in json_data:
		request.POST[element['name']] = element['value']

	return request


def get_profile(request):
	email = request.session.get('email')
	phonenumber = request.session.get('phonenumber')

	profile = None
	if email is not None:
		profile = UserProfile.objects.get(email=email)
	
	elif phonenumber is not None:
		profile = UserProfile.objects.get(phonenumber=phonenumber)

	return profile


def check_for_lockout(request, profile):
	url = None
	if profile.temp_lockout():
		messages.warning(
			request,
			"You have attempted to log in too many times. Please try again later."
		)
		url = reverse('profile:login')
		logout(request)

	return url

apps/user_profile/utils/mixins/views.py
import json

from django.http import JsonResponse
from django.views.generic import FormView

from user_profile.forms import PasswordValidationForm



class RequestFormMixin:
	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs.update({'request': self.request})
		return kwargs



def json_response_with_errors(form):
	data = {'error_list': form.errors}
	return JsonResponse(data, status=200)


class AjaxValidateFormMixin:
	def form_valid(self, form):		
		# Returns empty error dict to front end to enable submit button
		if self.request.is_ajax():
			return json_response_with_errors(form)
		
		form.save()
		return super().form_valid(form)

	def form_invalid(self, form):
		# Ajax validation
		if self.request.is_ajax():
			return json_response_with_errors(form)

		return super().form_invalid(form)


class ChangePasswordFormMixin(RequestFormMixin, AjaxValidateFormMixin):
	def post(self, *args, **kwargs):
		profile = self.profile
		self.request.POST = self.request.POST.copy()

		self.request.POST['email'] = profile.email
		self.request.POST['username'] = profile.user.username
		self.request.POST['first_name'] = profile.first_name
		self.request.POST['last_name'] = profile.last_name

		return super().post(self.request, **kwargs)



class VerifyPasswordContextMixin:
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context_name = "verify_password"

		if self.profile.validation_required():
			context[context_name] = PasswordValidationForm(self.request)

		return context

apps/user_profile/views.py
import datetime, json

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import (
	LogoutView,
	PasswordChangeView,
	PasswordResetView,
	PasswordResetConfirmView
)
from django.contrib.messages.views import SuccessMessageMixin
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import (
	DetailView,
	FormView,
	TemplateView,
	UpdateView,
	View
)

from phonenumber_field.phonenumber import PhoneNumber

from .forms import *
from .models import *
from .utils.helper_functions.views import *
from .utils.helper_functions.twilio import twilio_send_code
from .utils.mixins.access import *
from .utils.mixins.views import *



class CustomRegistrationView(AnonymousAccessMixin,
							SuccessMessageMixin,
							AjaxValidateFormMixin,
							FormView):
	form_class = CustomRegistrationForm
	template_name = 'auth/register.html'
	success_url = reverse_lazy('profile:login')
	success_message = "Successfully created account!"

	def post(self, *args, **kwargs):
		if self.request.is_ajax():
			deserialize_json(self.request)

		return super().post(self.request, **kwargs)


class CustomAuthenticationView(AnonymousAccessMixin,
								RequestFormMixin,
								AjaxValidateFormMixin,
								FormView):
	form_class = CustomAuthenticationForm
	template_name = 'auth/login.html'
	success_url = reverse_lazy('profile:home')

	def form_valid(self, form):
		username = self.request.POST['username']
		password = self.request.POST['password']

		user = authenticate(username=username, password=password)
		first_login = self.request.session.get('first_login')

		login(self.request, user)
		if first_login is not None:
			if self.request.is_ajax():
				url = reverse_lazy('profile:add_phone')
				data = {'url': url}
				return JsonResponse(data, status=200)

			return redirect('profile:add_phone')


		if self.request.is_ajax():
			url = reverse_lazy('profile:home')
			data = {'url': url}
			return JsonResponse(data, status=200)
		
		return redirect(self.success_url)


class LogoutView(LogoutView):
	next_page = 'profile:home'


class CustomPasswordChangeView(ChangeAccessMixin,
								SuccessMessageMixin,
								ChangePasswordFormMixin,
								FormView):
	form_class = CustomPasswordChangeForm
	template_name = 'auth/password_change_form.html'
	success_url = reverse_lazy('profile:login')
	success_message = "Your password has been changed."

	def form_invalid(self, form):
		if self.request.is_ajax():
			return super().form_invalid(form)
		
		incorrect = self.request.session.get('old_password_incorrect')
		if incorrect is not None:
			self.profile.add_attempt()
			url = check_for_lockout(self.request, self.profile)
			if url is not None:
				return redirect(url)

		return super().form_invalid(form)


class CustomPasswordResetView(AnonymousAccessMixin,
								RequestFormMixin,
								PasswordResetView):
	form_class = ResetForm
	success_url = reverse_lazy('profile:login')
	template_name = 'auth/password_reset_form.html'

	email_template_name = 'auth/password_reset_email.html'
	subject_template_name = 'auth/password_reset_subject.txt'
	html_email_template_name = "auth/password_reset_html_email.html"
	extra_email_context = None
	from_email = None
	title = ('Forgot Password')
	token_generator = default_token_generator

	def form_valid(self, form):
		phonenumber = form.cleaned_data.get('phonenumber')
		if phonenumber is not None:
			url = form.send_text()
			return redirect(url)


		url = form.pre_send_email()
		if url is not None:  #email doesn't exist in the system.
			return redirect(url)

		opts = {
			'request': self.request,
			'use_https': self.request.is_secure(),
			'token_generator': self.token_generator,
			'email_template_name': self.email_template_name,
			'html_email_template_name': self.html_email_template_name,
			'subject_template_name': self.subject_template_name,
			'extra_email_context': self.extra_email_context,
			'from_email': self.from_email,
		}

		# Sends email in inherited 'PasswordResetForm' method 'send_mail()'
		form.save(**opts)
		return redirect(self.success_url)


class CustomPasswordResetConfirmView(ResetAccessMixin,
									SuccessMessageMixin,
									ChangePasswordFormMixin,
									PasswordResetConfirmView):
	form_class = CustomSetPasswordForm
	success_url = reverse_lazy('profile:login')
	template_name = 'auth/password_reset_confirm.html'
	success_message = "Password has been successfully reset!"

	post_reset_login = False
	post_reset_login_backend = None
	reset_url_token = "set-password"
	title = "Enter new password"
	token_generator = default_token_generator

	profile = None

	def setup(self, request, *args, **kwargs):
		self.profile = get_profile(request)
		return super().setup(request, *args, **kwargs)


class RecoverUsernameView(AnonymousAccessMixin,
							RequestFormMixin,
							PasswordResetView):
	form_class = ResetForm
	template_name = 'auth/recover_username.html'
	success_url = reverse_lazy('profile:login')

	email_template_name = 'auth/recover_username_email.html'
	subject_template_name = 'auth/recover_username_subject.txt'
	html_email_template_name = 'auth/recover_username_html_email.html'
	extra_email_context = None
	from_email = None
	title = ('Forgot Username')
	token_generator = default_token_generator


	def form_valid(self, form):
		phonenumber = form.cleaned_data.get('phonenumber')
		if phonenumber is not None:
			url = form.send_text(reset_password=False)
			return redirect(url)


		url = form.pre_send_email(reset_password=False)
		if url is not None: 
			return redirect(url)

		email = self.request.POST['email']
		profile = UserProfile.objects.get(email=email)

		opts = {
			'request': self.request,
			'use_https': self.request.is_secure(),
			'token_generator': self.token_generator,
			'email_template_name': self.email_template_name,
			'html_email_template_name': self.html_email_template_name,
			'subject_template_name': self.subject_template_name,
			'extra_email_context': {'username': profile.user},
			'from_email': self.from_email,
		}

		form.save(**opts)
		return redirect(self.success_url)


# If JS is disabled
class PasswordValidationView(ValidationAccessMixin, RequestFormMixin, FormView):
	form_class = PasswordValidationForm
	template_name = 'user_profile/verify_password.html'
	success_url = reverse_lazy('profile:profile')
	
	def form_invalid(self, form):
		url = check_for_lockout(self.request, self.profile)
		if url is not None:
			return redirect(url)

		return super().form_invalid(form)


# If JS is enabled
def ajax_password_validation_view(request):
	if request.is_ajax():
		profile = request.user.userprofile

		form = PasswordValidationForm(request, request.POST)
		if form.is_valid():
			data = {'refresh': "Correct info."}
		else:
			data = {'error_list': form.errors}
			if profile.temp_lockout():
				data = {'refresh': "Too many attempts."}

		return JsonResponse(data, status=200)



class HomeView(TemplateView):
	template_name = 'user_profile/home.html'


class AddPhoneView(AddPhoneAccessMixin, RequestFormMixin, FormView):
	form_class = AddPhonenumberForm
	template_name = 'user_profile/add_phone.html'
	success_url = reverse_lazy('profile:phone_verification')

	def post(self, *args, **kwargs):	
		later = self.request.POST.get('later')
		if later is not None:
			self.request.session.pop('first_login', None)
			return redirect('profile:home')

		return super().post(self.request, **kwargs)

	def form_valid(self, form):
		self.request.session.pop('first_login', None)
		return super().form_valid(form)


class PhoneVerificationView(VerifyCodeAccessMixin,
							SuccessMessageMixin,
							RequestFormMixin,
							FormView):
	form_class = CodeVerificationForm
	template_name = 'user_profile/phone_verification.html'
	success_url = reverse_lazy('profile:profile')
	success_message = "Phone number has been verified!"

	def post(self, *args, **kwargs):
		send_again = self.request.POST.get('resend_code')

		if send_again is not None:
			twilio_send_code(self.profile, self.profile.phonenumber)
			messages.info(self.request, "Code has been resent to your phone.")
			return redirect(self.request.path_info)

		return super().post(*args, **kwargs)


class ProfileView(LoginAccessMixin, VerifyPasswordContextMixin, DetailView):
	model = UserProfile
	template_name = 'user_profile/profile.html'

	def get_object(self, queryset=None):
		return self.request.user


class UpdateProfileView(LoginAccessMixin,
						RequestFormMixin,
						VerifyPasswordContextMixin,
						UpdateView):
	form_class = UpdateProfileForm
	model = User
	template_name = 'user_profile/update_profile.html'

	def get_object(self, queryset=None):
		return self.request.user

	def post(self, *args, **kwargs):
		disable = self.request.POST.get('disable')
		if disable is not None:
			self.profile.disable_account()
			messages.warning(
				self.request, "Sorry to see you go. Contact us if you wanna come back!"
			)
			return redirect('profile:login')

		return super().post(*args, **kwargs)

	def get_success_url(self, **kwargs):
		url = self.request.session['url']
		del self.request.session['url']

		return url

apps/user_profile/templates/base.html
{% load static %}
{% load crispy_forms_tags %}
{% load user_profile_template_tags %}

<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- CSS -->
	<link rel="stylesheet" href="{% static 'user_profile/fontawesome/css/all.css' %}">
	<link rel="stylesheet" href="{% static 'user_profile/bootstrap/css/bootstrap.min.css' %}">
	
	<link rel="stylesheet" href="{% static 'user_profile/css/base.css' %}">
	<link rel="stylesheet" href="{% static 'user_profile/css/applications.css' %}">

	<style rel="stylesheet" type="text/css">{{ css|website }}</style>
	
	<title>{% block title %} {% endblock title %}</title>
</head>

<body>
	<noscript>
		<div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
			<p>If you want the full experience, turn JavaScript back on baby.</p>
		</div>
	</noscript>


	{% if verify_password %}
		<noscript>
			<meta HTTP-EQUIV="REFRESH" content="0; url={% url 'profile:password_validation' %}">
		</noscript>
		<button id="show-form" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-backdrop="static" data-keyboard="false" hidden></button>

		<div class="center">
			<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
			  <div class="modal-dialog mw-300" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <h5 class="modal-title center-block">Verify Password</h5>
			      </div>
			      <div class="modal-body" style="text-align:center">
			        <form method="post" action="{% url 'profile:ajax_password_validation' %}" class="verify-password-form form-popup">
			          {% csrf_token %}
			             <p class="text-error" id="error"></p>
			          {{verify_password.password|as_crispy_field}}<br>
			          <button type="submit" class="btn btn-primary w-full">Verify Password</button>

			        </form>
			      </div>

			    </div>
			  </div>
			</div>
		</div>
	{% endif %}


	<!-- NavBar -->
	<div class="script-element">
		<nav class="navbar navbar-expand-lg navbar-dark bt-color1 mb-3 mb-md-5" style="">
			<a class="navbar-brand" href="{% url 'profile:home' %}">Website Name</a>

			<!-- JS Enabled -->
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse ml-3" id="navbarSupportedContent">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item dropdown {% block article %} {% endblock article %}">
						<a class="nav-link" href="{% url 'article:category_list' %}">article</a>
					</li>
					<li class="nav-item dropdown {% block store %} {% endblock store %}">
						<a class="nav-link" href="{% url 'store:item_category_list' %}">Store</a>
					</li>
					<li class="nav-item dropdown {% block order_summary %} {% endblock order_summary %}">
						<a class="nav-link" href="{% url 'store:order_summary' %}">Order Summary</a>
					</li>
					{% if user.is_superuser %}
						<li class="nav-item dropdown">
							<a class="nav-link" href="{% url 'admin:login' %}">Admin</a>
						</li>
					{% endif %}

					{% if user.is_authenticated %}
						<li class="nav-item dropdown {% block profile %} {% endblock profile %}">
							<a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								{{user}}
							</a>
							<div class="dropdown-menu animate slideIn" aria-labelledby="navbarDropdown">
								<a class="dropdown-item" href="{% url 'profile:profile' %}">Profile</a>
								<a class="dropdown-item" href="{% url 'store:billing_profile' %}">Billing</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="{% url 'profile:logout' %}">Logout</a>
							</div>
						</li>
					{% else %}
						<li class="nav-item dropdown {% block home %} {% endblock home %}">
							<a class="nav-link" href="{% url 'profile:login' %}">Login</a>
						</li>					
					{% endif %}
				</ul>
			</div>

		</nav>
	</div>

	<!-- JS Disabled -->
	<noscript class="">
		<nav class="navbar navbar-expand-lg navbar-dark bt-color1">
			<a class="navbar-brand" href="{% url 'profile:home' %}">Website Name</a>

			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'article:category_list' %}">article</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'store:item_category_list' %}">Store</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'store:order_summary' %}">Order Summary</a>
				</li>
				{% if user.is_superuser %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'admin:login' %}">Admin</a>
					</li>
				{% endif %}

				{% if user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link" style="cursor:default">|</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" style="cursor:default">{{user}}:</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'profile:profile' %}">Profile</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'store:billing_profile' %}">Billing</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'profile:logout' %}">Logout</a>
					</li>
				{% else %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'profile:login' %}">Login</a>
					</li>
				{% endif %}
			</ul>

		</nav>
	</noscript>

	<!-- Messages -->
	<span id="random-error"></span>
	{% if messages %}
		{% for message in messages %}
		<div class="alert alert-{{message.tags}} alert-dismissible fade show text-center" role="alert">
			{{message|safe}}
			<button type="button" class="close script-element" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
		{% endfor %}
	{% endif %}


	<!-- Block Body -->
	<a id="verifyUrl" href="{% url 'profile:ajax_password_validation' %}"></a>
	<div class="container-fluid">{% block body %} {% endblock body %}</div>

	<!-- Footer -->
	<footer class="container-fluid mt-5">
		<div class="row bt-color2 text-white">
			<div class="col-sm-6 col-lg-4 mt-3 mb-3 pl-4 pl-md-5">
				<h3>Contact Us</h3>
				<span>(626)-398-2102</span>
				<br>template-email@gmail.com
			</div>

			<div class="col-sm-6 col-lg-5 mt-sm-3 mb-3 pl-4 pl-md-5">
				<h3>My Social Profile</h3>
				<a href=""><i class="fab fa-facebook mr-2"></i></a>
				<a href=""><i class="fab fa-twitter mr-2" style="color: #0084b4"></i></a>
				<a href=""><i class="fab fa-instagram"></i></a>
			</div>
		</div>

		<div class="row bt-color1">
			<center class="col-12 pb-3 pt-3 text-14">Gaabeeg &#169;</center>
		</div>
	</footer>
	<!-- Script -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<script src="{% static 'user_profile/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'user_profile/waypoints/lib/jquery.waypoints.min.js' %}"></script>
	<script src="{% static 'user_profile/waypoints/lib/shortcuts/infinite.min.js' %}"></script>


	<script type="text/javascript" src="{% static 'user_profile/js/reusable_code/token.js' %}"></script>
	<script type="text/javascript" src="{% static 'user_profile/js/reusable_code/data.js' %}"></script>
	<script type="text/javascript" src="{% static 'user_profile/js/reusable_code/functions.js' %}"></script>
	<script type="text/javascript">
		$(".script-element").show()
		verifyUrl = $("#verifyUrl").attr('href')
		
		if ($("#form-popup")){
			$("#show-form").click();
		}
	</script>
	{% block javascript %} {% endblock javascript %}
</body>
</html>

apps/user_profile/templates/reset_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

<head>{% block title %}Retrieve Username{% endblock title%}</head>

<body>
	{% block body %}
		<div class="row center border-l-grey border-round" id="reset-border">
			<img src="{% static 'user_profile/html_images/snoopy_woodstock.jpg' %}" alt="woodstock" class="col-md-6 img-fit img-outside" id="reset-img">

			<div class="col-md-6 center mw-290">
				<h4 align="center">{% block h4 %} {% endblock h4 %}</h4><hr>

				<form method="POST" class="single-submit">
					{% csrf_token %}
					<img src="{% static 'user_profile/html_images/snoopy_woodstock.jpg' %}" alt="woodstock" class="img-fluid img-inside">
	
					<p class="text-14 mt-3">Enter the email or phone number associated with your account and we'll send you {% block info %}{% endblock info%}.</p>


					{% if form.non_field_errors %}
					    {% for err in form.non_field_errors %}
					      <p class= "text-error error_message mt-3">{{ err }}</p>
					    {% endfor %}
					{% endif %}

					<div class="input-group mb-3">
						<div class="input-group-prepend">
							<span class="input-group-text" id="email-addon"><i class="fa fa-envelope"></i></span>
						</div>
							{{form.email}}
					</div>
					
					<div class="input-group mb-3">
						<div class="input-group-prepend">
							<span class="input-group-text" id="phone-addon"><i class="fa fa-phone"></i></span>
						</div>
						{{form.country_code}}{{form.area_code}}{{form.number}}
						{% if form.phonenumber.errors %}
						    {% for err in form.phonenumber.errors %}
						      <p class="text-error error_message mt-3">{{ err }}</p>
						    {% endfor %}
						{% endif %}
					</div>

					<button type="Submit"class="btn bt-color1 w-full">{% block button_title %} {% endblock button_title %}</button>

					<hr>
					<a href="{% url 'profile:login' %}"><center>Return to login</center></a>
				</form>
			</div>

		</div>
	{% endblock body %}
</body>